export default {
  learn: [
    'perfect store',
    'red bull products',
    'brand',
    'sales training',
    'my team',
    'newsletter',
    'segmentation guide',
    'glossary',
    'meetings',
  ],
  'perfect store': [
    'main placement',
    'permanent ambient placement',
    'permanent chilled placement',
    'temporary promotion placement',
    'availability',
    'shelf space',
    'pricing',
    'additional placements',
    'chilled cashier placements',
  ],
  'red bull products': [
    'energy drink',
    'sugar free',
    'zero',
    'editions',
    'organics',
  ],
  sell: ['insights', 'objection handling', 'best practice', 'deal sheets'],
  insights: [
    'main placement',
    'permanent ambient placement',
    'permanent chilled placement',
    'temporary promotion placement',
    'availability',
    'shelf space',
    'pricing',
    'additional placements',
    'chilled cashier placements',
    'energy drink',
    'sugar free',
    'zero',
    'editions',
    'shopper',
    'consumer',
    'retail',
    'impulse',
    'vip',
  ],
  'best practice': [
    'retail',
    'impulse',
    'main placement',
    'permanent ambient placement',
    'permanent chilled placement',
    'temporary promotion placement',
  ],
  execute: [
    'pos',
    'promo calendar',
    'consumer activations',
    'trade incentives',
    'vip contracts',
    'contracts',
    'accounts',
  ],
  pos: [
    'pos catalogue',
    'main placement',
    'permanent ambient',
    'permanent chilled',
    'temporary promotion',
    'in-store theatre',
    'visibility',
    'vending',
    'digital crowners',
    'pos organics',
    'consumer products',
    'consumer activations',
    'video instructions',
  ],
} as Record<string, string[]>;
