export const currencyList = [
  {
    country: 'Afghanistan',
    countryCode: 'AF',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Albania',
    countryCode: 'AL',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Algeria',
    countryCode: 'DZ',
    currencyCode: 'DZD',
    symbol: 'DA',
    symbolFormat: (n: number | string) => `${n} DA`,
  },
  {
    country: 'American Samoa',
    countryCode: 'AS',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Andorra',
    countryCode: 'AD',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Angola',
    countryCode: 'AO',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Anguilla',
    countryCode: 'AI',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Antarctica',
    countryCode: 'AQ',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Antigua And Barbuda',
    countryCode: 'AG',
    currencyCode: 'XCD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Argentina',
    countryCode: 'AR',
    currencyCode: 'ARS',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Armenia',
    countryCode: 'AM',
    currencyCode: 'AMD',
    symbol: '֏',
    symbolFormat: (n: number | string) => `${n}֏`,
  },
  {
    country: 'Aruba',
    countryCode: 'AW',
    currencyCode: 'AWG',
    symbol: 'Afl',
    symbolFormat: (n: number | string) => `Afl ${n}`,
  },
  {
    country: 'Ascension Island',
    countryCode: 'AC',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Australia',
    countryCode: 'AU',
    currencyCode: 'AUD',
    symbol: 'AU$',
    symbolFormat: (n: number | string) => `AU$${n}`,
  },
  {
    country: 'Austria',
    countryCode: 'AT',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Azerbaijan',
    countryCode: 'AZ',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Bahamas',
    countryCode: 'BS',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Bahrain',
    countryCode: 'BH',
    currencyCode: 'BHD',
    symbol: 'BD',
    symbolFormat: (n: number | string) => `${n} BD`,
  },
  {
    country: 'Bangladesh',
    countryCode: 'BD',
    currencyCode: 'BDT',
    symbol: '৳',
    symbolFormat: (n: number | string) => `৳${n}`,
  },
  {
    country: 'Barbados',
    countryCode: 'BB',
    currencyCode: 'BBD',
    symbol: 'Bds$',
    symbolFormat: (n: number | string) => `Bds$${n}`,
  },
  {
    country: 'Belarus',
    countryCode: 'BY',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Belgium',
    countryCode: 'BE',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Belize',
    countryCode: 'BZ',
    currencyCode: 'BZD',
    symbol: 'BZ$',
    symbolFormat: (n: number | string) => `BZ$${n}`,
  },
  {
    country: 'Benin',
    countryCode: 'BJ',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Bermuda',
    countryCode: 'BM',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Bhutan',
    countryCode: 'BT',
    currencyCode: 'BTN',
    symbol: 'Nu.',
    symbolFormat: (n: number | string) => `Nu.${n}`,
  },
  {
    country: 'Bolivia',
    countryCode: 'BO',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Bosnia And Herzegowina',
    countryCode: 'BA',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Botswana',
    countryCode: 'BW',
    currencyCode: 'BWP',
    symbol: 'P',
    symbolFormat: (n: number | string) => `P ${n}`,
  },
  {
    country: 'Bouvet Island',
    countryCode: 'BV',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Brazil',
    countryCode: 'BR',
    currencyCode: 'BRL',
    symbol: 'R$',
    symbolFormat: (n: number | string) => `R$${n}`,
  },
  {
    country: 'British Indian Ocean Territory',
    countryCode: 'IO',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Brunei Darussalam',
    countryCode: 'BN',
    currencyCode: 'BND',
    symbol: 'B$',
    symbolFormat: (n: number | string) => `B$${n}`,
  },
  {
    country: 'Bulgaria',
    countryCode: 'BG',
    currencyCode: 'BGN',
    symbol: 'BGN',
    symbolFormat: (n: number | string) => `BGN ${n}`,
  },
  {
    country: 'Burkina Faso',
    countryCode: 'BF',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Burundi',
    countryCode: 'BI',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Cambodia',
    countryCode: 'KH',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Cameroon',
    countryCode: 'CM',
    currencyCode: 'XAF',
    symbol: 'XAF',
    symbolFormat: (n: number | string) => `XAF ${n}`,
  },
  {
    country: 'Canada',
    countryCode: 'CA',
    currencyCode: 'CAD',
    symbol: 'C$',
    symbolFormat: (n: number | string) => `C$${n}`,
  },
  {
    country: 'Cape Verde',
    countryCode: 'CV',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Cayman Islands',
    countryCode: 'KY',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Central African Republic',
    countryCode: 'CF',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Chad',
    countryCode: 'TD',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Chile',
    countryCode: 'CL',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'China',
    countryCode: 'CN',
    currencyCode: 'CNY',
    symbol: '¥',
    symbolFormat: (n: number | string) => `¥${n}`,
  },
  {
    country: 'Christmas Island',
    countryCode: 'CX',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Cocos (Keeling) Islands',
    countryCode: 'CC',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Colombia',
    countryCode: 'CO',
    currencyCode: 'COP',
    symbol: 'COL$',
    symbolFormat: (n: number | string) => `COL$${n}`,
  },
  {
    country: 'Comoros',
    countryCode: 'KM',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Congo',
    countryCode: 'CG',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: "Congo, Democratic People's Republic",
    countryCode: 'CD',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Cook Islands',
    countryCode: 'CK',
    currencyCode: 'NZD',
    symbol: 'NZ$',
    symbolFormat: (n: number | string) => `NZ$${n}`,
  },
  {
    country: 'Costa Rica',
    countryCode: 'CR',
    currencyCode: 'CRC',
    symbol: '₡',
    symbolFormat: (n: number | string) => `₡${n}`,
  },
  {
    country: "Cote d'Ivoire",
    countryCode: 'CI',
    currencyCode: 'XOF',
    symbol: 'XOF',
    symbolFormat: (n: number | string) => `XOF ${n}`,
  },
  {
    country: 'Croatia (local name: Hrvatska)',
    countryCode: 'HR',
    currencyCode: 'HRK',
    symbol: 'kn',
    symbolFormat: (n: number | string) => `${n} kn`,
  },
  {
    country: 'Cuba',
    countryCode: 'CU',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Cyprus',
    countryCode: 'CY',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Czech Republic',
    countryCode: 'CZ',
    currencyCode: 'CZK',
    symbol: 'Kč',
    symbolFormat: (n: number | string) => `${n} Kč`,
  },
  {
    country: 'Denmark',
    countryCode: 'DK',
    currencyCode: 'DKK',
    symbol: 'Kr.',
    symbolFormat: (n: number | string) => `${n} Kr.`,
  },
  {
    country: 'Djibouti',
    countryCode: 'DJ',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Dominica',
    countryCode: 'DM',
    currencyCode: 'XCD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Dominican Republic',
    countryCode: 'DO',
    currencyCode: 'DOP',
    symbol: 'RD$',
    symbolFormat: (n: number | string) => `RD$${n}`,
  },
  {
    country: 'East Timor',
    countryCode: 'TP',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Ecuador',
    countryCode: 'EC',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Egypt',
    countryCode: 'EG',
    currencyCode: 'EGP',
    symbol: 'E£',
    symbolFormat: (n: number | string) => `E£ ${n}`,
  },
  {
    country: 'El Salvador',
    countryCode: 'SV',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Equatorial Guinea',
    countryCode: 'GQ',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Eritrea',
    countryCode: 'ER',
    currencyCode: 'ERN',
    symbol: 'Nkf',
    symbolFormat: (n: number | string) => `${n} Nkf`,
  },
  {
    country: 'Estonia',
    countryCode: 'EE',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Ethiopia',
    countryCode: 'ET',
    currencyCode: 'ETB',
    symbol: 'Br',
    symbolFormat: (n: number | string) => `${n} Br`,
  },
  {
    country: 'Falkland Islands (Malvinas)',
    countryCode: 'FK',
    currencyCode: 'FKP',
    symbol: 'FK£',
    symbolFormat: (n: number | string) => `FK£ ${n}`,
  },
  {
    country: 'Faroe Islands',
    countryCode: 'FO',
    currencyCode: 'DKK',
    symbol: 'Kr.',
    symbolFormat: (n: number | string) => `${n} Kr.`,
  },
  {
    country: 'Fiji',
    countryCode: 'FJ',
    currencyCode: 'FJD',
    symbol: 'FJ$',
    symbolFormat: (n: number | string) => `FJ$${n}`,
  },
  {
    country: 'Finland',
    countryCode: 'FI',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'France',
    countryCode: 'FR',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'French Guiana',
    countryCode: 'GF',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'French Polynesia',
    countryCode: 'PF',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'French Southern Territories',
    countryCode: 'TF',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Gabon',
    countryCode: 'GA',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Gambia',
    countryCode: 'GM',
    currencyCode: 'GMD',
    symbol: 'GMD',
    symbolFormat: (n: number | string) => `GMD ${n}`,
  },
  {
    country: 'Georgia (Sakartvelo)',
    countryCode: 'GE',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Germany',
    countryCode: 'DE',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Ghana',
    countryCode: 'GH',
    currencyCode: 'GHC',
    symbol: 'GH₵',
    symbolFormat: (n: number | string) => `GH₵ ${n}`,
  },
  {
    country: 'Gibraltar',
    countryCode: 'GI',
    currencyCode: 'GBP',
    symbol: '£',
    symbolFormat: (n: number | string) => `£${n}`,
  },
  {
    country: 'Greece',
    countryCode: 'GR',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Greenland',
    countryCode: 'GL',
    currencyCode: 'DKK',
    symbol: 'Kr.',
    symbolFormat: (n: number | string) => `${n} Kr.`,
  },
  {
    country: 'Grenada',
    countryCode: 'GD',
    currencyCode: 'XCD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Guadeloupe',
    countryCode: 'GP',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Guam',
    countryCode: 'GU',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Guatemala',
    countryCode: 'GT',
    currencyCode: 'GTQ',
    symbol: 'Q',
    symbolFormat: (n: number | string) => `${n} Q`,
  },
  {
    country: 'Guernsey',
    countryCode: 'GG',
    currencyCode: 'GBP',
    symbol: '£',
    symbolFormat: (n: number | string) => `£${n}`,
  },
  {
    country: 'Guinea',
    countryCode: 'GN',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Guinea-Bissau',
    countryCode: 'GW',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Guyana',
    countryCode: 'GY',
    currencyCode: 'GYD',
    symbol: 'GY$',
    symbolFormat: (n: number | string) => `GY$${n}`,
  },
  {
    country: 'Haiti',
    countryCode: 'HT',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Heard And Mc Donald Islands',
    countryCode: 'HM',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Honduras',
    countryCode: 'HN',
    currencyCode: 'HNL',
    symbol: 'HNL',
    symbolFormat: (n: number | string) => `HNL ${n}`,
  },
  {
    country: 'Hong Kong',
    countryCode: 'HK',
    currencyCode: 'HKD',
    symbol: 'HK$',
    symbolFormat: (n: number | string) => `HK$${n}`,
  },
  {
    country: 'Hungary',
    countryCode: 'HU',
    currencyCode: 'HUF',
    symbol: 'Ft',
    symbolFormat: (n: number | string) => `${n} Ft`,
  },
  {
    country: 'Iceland',
    countryCode: 'IS',
    currencyCode: 'ISK',
    symbol: 'kr',
    symbolFormat: (n: number | string) => `${n} kr`,
  },
  {
    country: 'India',
    countryCode: 'IN',
    currencyCode: 'INR',
    symbol: '₹',
    symbolFormat: (n: number | string) => `₹${n}`,
  },
  {
    country: 'Indonesia',
    countryCode: 'ID',
    currencyCode: 'IDR',
    symbol: 'Rp',
    symbolFormat: (n: number | string) => `Rp ${n}`,
  },
  {
    country: 'Iran (Islamic Republic Of)',
    countryCode: 'IR',
    currencyCode: 'IRR',
    symbol: 'IRR',
    symbolFormat: (n: number | string) => `IRR ${n}`,
  },
  {
    country: 'Iraq',
    countryCode: 'IQ',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Ireland',
    countryCode: 'IE',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Isle of Man',
    countryCode: 'IM',
    currencyCode: 'GBP',
    symbol: '£',
    symbolFormat: (n: number | string) => `£${n}`,
  },
  {
    country: 'Israel',
    countryCode: 'IL',
    currencyCode: 'ILS',
    symbol: '₪',
    symbolFormat: (n: number | string) => `₪${n}`,
  },
  {
    country: 'Italy',
    countryCode: 'IT',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Jamaica',
    countryCode: 'JM',
    currencyCode: 'JMD',
    symbol: 'JA$',
    symbolFormat: (n: number | string) => `JA$${n}`,
  },
  {
    country: 'Japan',
    countryCode: 'JP',
    currencyCode: 'JPY',
    symbol: '¥',
    symbolFormat: (n: number | string) => `¥${n}`,
  },
  {
    country: 'Jersey (Island)',
    countryCode: 'JE',
    currencyCode: 'GBP',
    symbol: '£',
    symbolFormat: (n: number | string) => `£${n}`,
  },
  {
    country: 'Jordan',
    countryCode: 'JO',
    currencyCode: 'JOD',
    symbol: 'JOD',
    symbolFormat: (n: number | string) => `JOD ${n}`,
  },
  {
    country: 'Kazakhstan',
    countryCode: 'KZ',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Kenya',
    countryCode: 'KE',
    currencyCode: 'KES',
    symbol: 'KSh',
    symbolFormat: (n: number | string) => `KSh ${n}`,
  },
  {
    country: 'Kiribati',
    countryCode: 'KI',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: "Korea, Democratic People's Republic Of",
    countryCode: 'KP',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Korea, Republic Of',
    countryCode: 'KR',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Kuwait',
    countryCode: 'KW',
    currencyCode: 'KWD',
    symbol: 'KD',
    symbolFormat: (n: number | string) => `${n} KD`,
  },
  {
    country: 'Kyrgyzstan',
    countryCode: 'KG',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: "Lao People's Democratic Republic",
    countryCode: 'LA',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Latvia',
    countryCode: 'LV',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Lebanon',
    countryCode: 'LB',
    currencyCode: 'LBP',
    symbol: 'LBP',
    symbolFormat: (n: number | string) => `LBP ${n}`,
  },
  {
    country: 'Lesotho',
    countryCode: 'LS',
    currencyCode: 'ZAR',
    symbol: 'R',
    symbolFormat: (n: number | string) => `R${n}`,
  },
  {
    country: 'Liberia',
    countryCode: 'LR',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Libyan Arab Jamahiriya',
    countryCode: 'LY',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Liechtenstein',
    countryCode: 'LI',
    currencyCode: 'CHF',
    symbol: 'Fr.',
    symbolFormat: (n: number | string) => `${n} Fr.`,
  },
  {
    country: 'Lithuania',
    countryCode: 'LT',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Luxembourg',
    countryCode: 'LU',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Macau',
    countryCode: 'MO',
    currencyCode: 'MOP',
    symbol: 'MOP$',
    symbolFormat: (n: number | string) => `MOP$${n}`,
  },
  {
    country: 'Macedonia, The Former Yugoslav Republic Of',
    countryCode: 'MK',
    currencyCode: 'MKD',
    symbol: 'MKD',
    symbolFormat: (n: number | string) => `MKD ${n}`,
  },
  {
    country: 'Madagascar',
    countryCode: 'MG',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Malawi',
    countryCode: 'MW',
    currencyCode: 'MWK',
    symbol: 'MK',
    symbolFormat: (n: number | string) => `MK ${n}`,
  },
  {
    country: 'Malaysia',
    countryCode: 'MY',
    currencyCode: 'MYR',
    symbol: 'RM',
    symbolFormat: (n: number | string) => `RM ${n}`,
  },
  {
    country: 'Maldives',
    countryCode: 'MV',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Mali',
    countryCode: 'ML',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Malta',
    countryCode: 'MT',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Marshall Islands',
    countryCode: 'MH',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Martinique',
    countryCode: 'MQ',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Mauritania',
    countryCode: 'MR',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Mauritius',
    countryCode: 'MU',
    currencyCode: 'MUR',
    symbol: 'Rs',
    symbolFormat: (n: number | string) => `Rs ${n}`,
  },
  {
    country: 'Mayotte',
    countryCode: 'YT',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Mexico',
    countryCode: 'MX',
    currencyCode: 'MXN',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Micronesia, Federated States Of',
    countryCode: 'FM',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Moldova, Republic Of',
    countryCode: 'MD',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Monaco',
    countryCode: 'MC',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Mongolia',
    countryCode: 'MN',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Montserrat',
    countryCode: 'MS',
    currencyCode: 'XCD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Morocco',
    countryCode: 'MA',
    currencyCode: 'MAD',
    symbol: 'MAD',
    symbolFormat: (n: number | string) => `MAD ${n}`,
  },
  {
    country: 'Mozambique',
    countryCode: 'MZ',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Myanmar',
    countryCode: 'MM',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Namibia',
    countryCode: 'NA',
    currencyCode: 'NAD',
    symbol: 'N$',
    symbolFormat: (n: number | string) => `N$${n}`,
  },
  {
    country: 'Nauru',
    countryCode: 'NR',
    currencyCode: 'AUD',
    symbol: 'AU$',
    symbolFormat: (n: number | string) => `AU$${n}`,
  },
  {
    country: 'Nepal',
    countryCode: 'NP',
    currencyCode: 'NPR',
    symbol: 'रू',
    symbolFormat: (n: number | string) => `रू${n}`,
  },
  {
    country: 'Netherlands',
    countryCode: 'NL',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Netherlands Antilles',
    countryCode: 'AN',
    currencyCode: 'ANG',
    symbol: 'ƒ',
    symbolFormat: (n: number | string) => `ƒ${n}`,
  },
  {
    country: 'New Caledonia',
    countryCode: 'NC',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'New Zealand',
    countryCode: 'NZ',
    currencyCode: 'NZD',
    symbol: 'NZ$',
    symbolFormat: (n: number | string) => `NZ$${n}`,
  },
  {
    country: 'Nicaragua',
    countryCode: 'NI',
    currencyCode: 'NIO',
    symbol: 'C$',
    symbolFormat: (n: number | string) => `C$${n}`,
  },
  {
    country: 'Niger',
    countryCode: 'NE',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Nigeria',
    countryCode: 'NG',
    currencyCode: 'NGN',
    symbol: '₦',
    symbolFormat: (n: number | string) => `₦${n}`,
  },
  {
    country: 'Niue',
    countryCode: 'NU',
    currencyCode: 'NZD',
    symbol: 'NZ$',
    symbolFormat: (n: number | string) => `NZ$${n}`,
  },
  {
    country: 'Norfolk Island',
    countryCode: 'NF',
    currencyCode: 'AUD',
    symbol: 'AU$',
    symbolFormat: (n: number | string) => `AU$${n}`,
  },
  {
    country: 'Northern Mariana Islands',
    countryCode: 'MP',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Norway',
    countryCode: 'NO',
    currencyCode: 'NOK',
    symbol: 'kr',
    symbolFormat: (n: number | string) => `${n} kr`,
  },
  {
    country: 'Oman',
    countryCode: 'OM',
    currencyCode: 'OMR',
    symbol: 'OMR',
    symbolFormat: (n: number | string) => `OMR ${n}`,
  },
  {
    country: 'Pakistan',
    countryCode: 'PK',
    currencyCode: 'PKR',
    symbol: 'Rs',
    symbolFormat: (n: number | string) => `Rs ${n}`,
  },
  {
    country: 'Palau',
    countryCode: 'PW',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Palestinian Territories',
    countryCode: 'PS',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Panama',
    countryCode: 'PA',
    currencyCode: 'PAB',
    symbol: 'B/.',
    symbolFormat: (n: number | string) => `B/. ${n}`,
  },
  {
    country: 'Papua New Guinea',
    countryCode: 'PG',
    currencyCode: 'PGK',
    symbol: 'K',
    symbolFormat: (n: number | string) => `K ${n}`,
  },
  {
    country: 'Paraguay',
    countryCode: 'PY',
    currencyCode: 'PYG',
    symbol: '₲',
    symbolFormat: (n: number | string) => `₲${n}`,
  },
  {
    country: 'Peru',
    countryCode: 'PE',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Philippines',
    countryCode: 'PH',
    currencyCode: 'PHP',
    symbol: '₱',
    symbolFormat: (n: number | string) => `₱${n}`,
  },
  {
    country: 'Pitcairn',
    countryCode: 'PN',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Poland',
    countryCode: 'PL',
    currencyCode: 'PLN',
    symbol: 'zł',
    symbolFormat: (n: number | string) => `${n}zł`,
  },
  {
    country: 'Portugal',
    countryCode: 'PT',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Puerto Rico',
    countryCode: 'PR',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Qatar',
    countryCode: 'QA',
    currencyCode: 'QAR',
    symbol: 'QAR',
    symbolFormat: (n: number | string) => `QAR ${n}`,
  },
  {
    country: 'Reunion',
    countryCode: 'RE',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Romania',
    countryCode: 'RO',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Russia',
    countryCode: 'RU',
    currencyCode: 'RUB',
    symbol: '₽',
    symbolFormat: (n: number | string) => `${n}₽`,
  },
  {
    country: 'Rwanda',
    countryCode: 'RW',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Saint Kitts And Nevis',
    countryCode: 'KN',
    currencyCode: 'XCD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Saint Lucia',
    countryCode: 'LC',
    currencyCode: 'XCD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Saint Vincent And The Grenadines',
    countryCode: 'VC',
    currencyCode: 'XCD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Samoa',
    countryCode: 'WS',
    currencyCode: 'WST',
    symbol: 'WS$',
    symbolFormat: (n: number | string) => `WS$${n}`,
  },
  {
    country: 'San Marino',
    countryCode: 'SM',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Sao Tome And Principe',
    countryCode: 'ST',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Saudi Arabia',
    countryCode: 'SA',
    currencyCode: 'SAR',
    symbol: 'SAR',
    symbolFormat: (n: number | string) => `SAR ${n}`,
  },
  {
    country: 'Senegal',
    countryCode: 'SN',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Serbia and Montenegro',
    countryCode: 'CS',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Seychelles',
    countryCode: 'SC',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Sierra Leone',
    countryCode: 'SL',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Singapore',
    countryCode: 'SG',
    currencyCode: 'SGD',
    symbol: 'S$',
    symbolFormat: (n: number | string) => `S$${n}`,
  },
  {
    country: 'Slovakia (Slovak Republic)',
    countryCode: 'SK',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Slovenia',
    countryCode: 'SI',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Solomon Islands',
    countryCode: 'SB',
    currencyCode: 'SBD',
    symbol: 'SI$',
    symbolFormat: (n: number | string) => `SI$${n}`,
  },
  {
    country: 'Somalia',
    countryCode: 'SO',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'South Africa',
    countryCode: 'ZA',
    currencyCode: 'ZAR',
    symbol: 'R',
    symbolFormat: (n: number | string) => `R${n}`,
  },
  {
    country: 'South Georgia And The South Sandwich Islands',
    countryCode: 'GS',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Spain',
    countryCode: 'ES',
    currencyCode: 'EUR',
    symbol: '€',
    symbolFormat: (n: number | string) => `€${n}`,
  },
  {
    country: 'Sri Lanka',
    countryCode: 'LK',
    currencyCode: 'LKR',
    symbol: 'Rs',
    symbolFormat: (n: number | string) => `Rs ${n}`,
  },
  {
    country: 'St. Helena',
    countryCode: 'SH',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'St. Pierre And Miquelon',
    countryCode: 'PM',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Sudan',
    countryCode: 'SD',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Suriname',
    countryCode: 'SR',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Svalbard And Jan Mayen Islands',
    countryCode: 'SJ',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Swaziland',
    countryCode: 'SZ',
    currencyCode: 'SZL',
    symbol: 'E',
    symbolFormat: (n: number | string) => `E${n}`,
  },
  {
    country: 'Sweden',
    countryCode: 'SE',
    currencyCode: 'SEK',
    symbol: 'kr',
    symbolFormat: (n: number | string) => `${n} kr`,
  },
  {
    country: 'Switzerland',
    countryCode: 'CH',
    currencyCode: 'CHF',
    symbol: 'Fr.',
    symbolFormat: (n: number | string) => `${n} Fr.`,
  },
  {
    country: 'Syrian Arab Republic',
    countryCode: 'SY',
    currencyCode: 'SYP',
    symbol: 'SYP',
    symbolFormat: (n: number | string) => `SYP ${n}`,
  },
  {
    country: 'Taiwan',
    countryCode: 'TW',
    currencyCode: 'TWD',
    symbol: 'NT$',
    symbolFormat: (n: number | string) => `NT$${n}`,
  },
  {
    country: 'Tajikistan',
    countryCode: 'TJ',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Tanzania, United Republic Of',
    countryCode: 'TZ',
    currencyCode: 'TZS',
    symbol: 'TZS',
    symbolFormat: (n: number | string) => `TZS ${n}`,
  },
  {
    country: 'Thailand',
    countryCode: 'TH',
    currencyCode: 'THB',
    symbol: '฿',
    symbolFormat: (n: number | string) => `฿${n}`,
  },
  {
    country: 'Togo',
    countryCode: 'TG',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Tokelau',
    countryCode: 'TK',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Tonga',
    countryCode: 'TO',
    currencyCode: 'TOP',
    symbol: 'T$',
    symbolFormat: (n: number | string) => `T$${n}`,
  },
  {
    country: 'Trinidad And Tobago',
    countryCode: 'TT',
    currencyCode: 'TTD',
    symbol: 'TT$',
    symbolFormat: (n: number | string) => `TT$${n}`,
  },
  {
    country: 'Tunisia',
    countryCode: 'TN',
    currencyCode: 'TND',
    symbol: 'TND',
    symbolFormat: (n: number | string) => `TND ${n}`,
  },
  {
    country: 'Turkey',
    countryCode: 'TR',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Turkmenistan',
    countryCode: 'TM',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Turks And Caicos Islands',
    countryCode: 'TC',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Tuvalu',
    countryCode: 'TV',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'U.S. Minor Outlying Islands',
    countryCode: 'UM',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Uganda',
    countryCode: 'UG',
    currencyCode: 'UGX',
    symbol: 'USh',
    symbolFormat: (n: number | string) => `USh ${n}`,
  },
  {
    country: 'Ukraine',
    countryCode: 'UA',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'United Arab Emirates',
    countryCode: 'AE',
    currencyCode: 'AED',
    symbol: 'AED',
    symbolFormat: (n: number | string) => `AED ${n}`,
  },
  {
    country: 'United Kingdom',
    countryCode: 'UK',
    currencyCode: 'GBP',
    symbol: '£',
    symbolFormat: (n: number | string) => `£${n}`,
  },
  {
    country: 'United States',
    countryCode: 'US',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Uruguay',
    countryCode: 'UY',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Uzbekistan',
    countryCode: 'UZ',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Vanuatu',
    countryCode: 'VU',
    currencyCode: 'VUV',
    symbol: 'VT',
    symbolFormat: (n: number | string) => `${n}VT`,
  },
  {
    country: 'Vatican City State (Holy See)',
    countryCode: 'VA',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Venezuela',
    countryCode: 'VE',
    currencyCode: 'VEB',
    symbol: 'Bs.',
    symbolFormat: (n: number | string) => `${n} Bs.`,
  },
  {
    country: 'Viet Nam',
    countryCode: 'VN',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Virgin Islands (British)',
    countryCode: 'VG',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Virgin Islands (U.S.)',
    countryCode: 'VI',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Wallis And Futuna Islands',
    countryCode: 'WF',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Western Sahara',
    countryCode: 'EH',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Yemen',
    countryCode: 'YE',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Zambia',
    countryCode: 'ZM',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
  {
    country: 'Zimbabwe',
    countryCode: 'ZW',
    currencyCode: 'USD',
    symbol: '$',
    symbolFormat: (n: number | string) => `$${n}`,
  },
] as const;
