apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: btc-operation-ci-cd
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      resources:
        requests:
          memory: "2048Mi"
          cpu: "1000m"
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
