import { Channel, Story } from '@redbull/services';

export const mockChannelNav: Record<number, Channel[]> = {
  21074: [
    {
      defaultSortBy: 'date',
      description: '',
      id: 208996,
      isFeed: false,
      isHidden: false,
      isReadable: true,
      isSubscribed: false,
      isWritable: true,
      name: 'Contracts (DE)',
      storyCount: 0,
      thumbnail: '',
      type: 'channel',
      stories: [],
    },
    {
      defaultSortBy: 'date',
      description: '',
      id: 208977,
      isFeed: false,
      isHidden: false,
      isReadable: true,
      isSubscribed: false,
      isWritable: true,
      name: 'Contracts (ZA-Cape Coastal)',
      storyCount: 1,
      thumbnail: '',
      type: 'channel',
      stories: [{} as Story],
    },
    {
      defaultSortBy: 'date',
      description: '',
      id: 208986,
      isFeed: false,
      isHidden: false,
      isReadable: true,
      isSubscribed: false,
      isWritable: true,
      name: 'Contracts (ZA-Inland North)',
      storyCount: 3,
      thumbnail: '',
      type: 'channel',
      stories: [{} as Story, {} as Story, {} as Story],
    },
  ],
};
